<a href="https://colab.research.google.com/github/viniciusaze/python-ds/blob/main/pandas_i_o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas I/O:

Trabalhando com diferentes formatos de arquivos

# Arquivos CSV

In [50]:
import pandas as pd

In [51]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data.csv'
dados_mercado = pd.read_csv(url)
dados_mercado.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [52]:
url_2 = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'
dados_mercado2 = pd.read_csv(url_2, sep=';')
dados_mercado2.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [53]:
dados_mercado_primeiras_linhas = pd.read_csv(url,nrows=5)
dados_mercado_primeiras_linhas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [54]:
dados_mercado_selecao_colunas = pd.read_csv(url,usecols=['Id', 'Year_Birth', 'Income',])
dados_mercado_selecao_colunas

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [55]:
dados_mercado_selecao_colunas = pd.read_csv(url,usecols=[0, 1, 4])
dados_mercado_selecao_colunas

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [56]:
dados_mercado_selecao_colunas.to_csv('clientes_mercado.csv', index=False)

In [57]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')
clientes_mercado

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

# Arquivos Excel

In [58]:
url = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'
# Não conseguimos ter acesso ao dado bruto. Então como leremos o arquivo?
# Depois de .xlsx, colocaremos um símbolo de interrogação e passar o parâmetro raw=True para
# trazer o arquivo bruto.

In [59]:
dados_co2 = pd.read_excel(url)

In [60]:
dados_co2.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Oléo  Gás  Cimento  \
0  Afeganistão                AFG  1750    0.0     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    0.0     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    0.0     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    0.0     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    0.0     NaN   NaN  NaN      NaN   

   Queima  Outro  Per Capita  
0     NaN    NaN         NaN  
1     NaN    NaN         NaN  
2     NaN    NaN         NaN  
3     NaN    NaN         NaN  
4     NaN    NaN         NaN

In [61]:
pd.ExcelFile(url).sheet_names
# Para descobrir se há mais páginas, usaremos uma classe da biblioteca Pandas chamada ExcelFile().
# Entre os parênteses, passaremos a URL. Depois, empregamos o atributo sheet_names (nome das páginas)

['emissoes_C02', 'emissoes_percapita', 'fontes']

In [62]:
percapita = pd.read_excel(url, sheet_name=1)

In [63]:
percapita.head()

País ISO 3166-1 alpha-3   Ano  Total  Carvão  Óleo  Gás  Cimento  \
0  Afeganistão                AFG  1750    NaN     NaN   NaN  NaN      NaN   
1  Afeganistão                AFG  1751    NaN     NaN   NaN  NaN      NaN   
2  Afeganistão                AFG  1752    NaN     NaN   NaN  NaN      NaN   
3  Afeganistão                AFG  1753    NaN     NaN   NaN  NaN      NaN   
4  Afeganistão                AFG  1754    NaN     NaN   NaN  NaN      NaN   

   Queima  Outro  
0     NaN    NaN  
1     NaN    NaN  
2     NaN    NaN  
3     NaN    NaN  
4     NaN    NaN

In [64]:
fontes = pd.read_excel(url, sheet_name=2)

In [65]:
fontes.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

**Parâmetro usecols**

Entre outros parâmetros da função read_excel(), existe o usecols, com o qual especificamos as colunas que queremos mostrar. Vamos explorá-lo, a seguir.

Criaremos uma variável chamada intevalo e chamaremos a função read_excel() da biblioteca Pandas. No primeiro parâmetro, passaremos a URL. No segundo, definiremos o nome da página, sheet_name='emissoes_C02'. No terceiro, indicaremos o intervalo desejado, com usecols= 'A:D'. Como aprendemos anteriormente, as colunas são nomeadas por letras. Ao indicar A:D, selecionamos o intervalo da coluna A até a coluna D:

In [66]:
intervalo = pd.read_excel(url, sheet_name=0, usecols='A:D')

In [67]:
intervalo.head()

País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750    0.0
1  Afeganistão                AFG  1751    0.0
2  Afeganistão                AFG  1752    0.0
3  Afeganistão                AFG  1753    0.0
4  Afeganistão                AFG  1754    0.0

In [68]:
intervalo_2 = pd.read_excel(url, sheet_name=0, usecols='A:D', nrows=10)

In [69]:
intervalo_2

País ISO 3166-1 alpha-3   Ano  Total
0  Afeganistão                AFG  1750      0
1  Afeganistão                AFG  1751      0
2  Afeganistão                AFG  1752      0
3  Afeganistão                AFG  1753      0
4  Afeganistão                AFG  1754      0
5  Afeganistão                AFG  1755      0
6  Afeganistão                AFG  1756      0
7  Afeganistão                AFG  1757      0
8  Afeganistão                AFG  1758      0
9  Afeganistão                AFG  1759      0

In [70]:
percapita.to_excel('co2_percapita.xlsx', index=False)
# Salvando em excel

In [71]:
pd.read_excel('/content/co2_percapita.xlsx')

País ISO 3166-1 alpha-3   Ano      Total     Carvão       Óleo  \
0      Afeganistão                AFG  1750        NaN        NaN        NaN   
1      Afeganistão                AFG  1751        NaN        NaN        NaN   
2      Afeganistão                AFG  1752        NaN        NaN        NaN   
3      Afeganistão                AFG  1753        NaN        NaN        NaN   
4      Afeganistão                AFG  1754        NaN        NaN        NaN   
...            ...                ...   ...        ...        ...        ...   
63099       Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100       Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101       Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102       Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103       Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gás   Cimento   Queima    Outro  
0            NaN       NaN      NaN      NaN  
1            NaN       NaN      NaN      NaN  
2            NaN       NaN      NaN      NaN  
3            NaN       NaN      NaN      NaN  
4            NaN       NaN      NaN      NaN  
...          ...       ...      ...      ...  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0  

[63104 rows x 10 columns]

# Google Planilhas

In [72]:
'https://docs.google.com/spreadsheets/d/1yjFVfP4nBbctvACv3nXsSbashOTt19U4l-P_82rZ4Rk/edit?usp=sharing'

'https://docs.google.com/spreadsheets/d/1yjFVfP4nBbctvACv3nXsSbashOTt19U4l-P_82rZ4Rk/edit?usp=sharing'

In [73]:
sheet_id = '1yjFVfP4nBbctvACv3nXsSbashOTt19U4l-P_82rZ4Rk'

In [74]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [75]:
dados_co2_sheets = pd.read_csv(url)

In [76]:
dados_co2_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Oléo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750     0    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751     0    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752     0    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753     0    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754     0    NaN  NaN  NaN     NaN    NaN   

  Outro Per Capita  
0   NaN        NaN  
1   NaN        NaN  
2   NaN        NaN  
3   NaN        NaN  
4   NaN        NaN

In [77]:
sheet_id = '1yjFVfP4nBbctvACv3nXsSbashOTt19U4l-P_82rZ4Rk'
sheet_name = 'emissoes_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [78]:
percapita_sheets = pd.read_csv(url_percapita)

In [79]:
percapita_sheets.head()

País ISO 3166-1 alpha-3   Ano Total Carvão Óleo  Gás Cimento Queima  \
0  Afeganistão                AFG  1750   NaN    NaN  NaN  NaN     NaN    NaN   
1  Afeganistão                AFG  1751   NaN    NaN  NaN  NaN     NaN    NaN   
2  Afeganistão                AFG  1752   NaN    NaN  NaN  NaN     NaN    NaN   
3  Afeganistão                AFG  1753   NaN    NaN  NaN  NaN     NaN    NaN   
4  Afeganistão                AFG  1754   NaN    NaN  NaN  NaN     NaN    NaN   

   Outro  
0    NaN  
1    NaN  
2    NaN  
3    NaN  
4    NaN

In [80]:
sheet_id = '1yjFVfP4nBbctvACv3nXsSbashOTt19U4l-P_82rZ4Rk'
sheet_name = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [81]:
fontes_sheets = pd.read_csv(url_fontes)

In [82]:
fontes_sheets.head()

País ISO 3166-1 alpha-3   Ano   Total  Carvão    Oléo     Gás  \
0  Afeganistão                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afeganistão                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afeganistão                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afeganistão                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afeganistão                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cimento  Queima   Outro Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

# Aquivos JSON

In [85]:
dados_pacientes = pd.read_json('/content/pacientes.json')

In [86]:
dados_pacientes

ID_paciente Doenca_cardiaca    IMC Fumante Consumo_alcool  AVC  \
0              0             Nao  16.60     Sim            Nao  Nao   
1              1             Nao  20.34     Nao            Nao  Sim   
2              2             Nao  26.58     Sim            Nao  Nao   
3              3             Nao  24.21     Nao            Nao  Nao   
4              4             Nao  23.71     Nao            Nao  Nao   
..           ...             ...    ...     ...            ...  ...   
995          995             Nao  28.29     Sim            Nao  Nao   
996          996             Nao  25.69     Sim            Nao  Nao   
997          997             Sim  26.99     Nao            Nao  Nao   
998          998             Nao  44.29     Nao            Nao  Nao   
999          999             Nao  25.83     Nao            Nao  Nao   

     Saude_fisica  Saude_mental Dificuldade_caminhar Sexo_biologico  \
0               3            30                  Nao       Feminino   
1               0             0                  Nao       Feminino   
2              20            30                  Nao      Masculino   
3               0             0                  Nao       Feminino   
4              28             0                  Sim       Feminino   
..            ...           ...                  ...            ...   
995            10            20                  Nao       Feminino   
996             0             0                  Nao       Feminino   
997             1             0                  Nao      Masculino   
998            30             0                  Sim       Feminino   
999             0             0                  Nao      Masculino   

    Faixa_etaria    Raca Diabetes Atividade_fisica Saude_geral  Horas_sono  \
0          55-59  Branca      Sim              Sim   Muito boa           5   
1        80 ou +  Branca      Nao              Sim   Muito boa           7   
2          65-69  Branca      Sim              Sim    Razoavel           8   
3          75-79  Branca      Nao               No         Boa           6   
4          40-44  Branca      Nao              Sim   Muito boa           8   
..           ...     ...      ...              ...         ...         ...   
995        65-69   Preta      Sim              Sim    Razoavel           8   
996        75-79  Branca      Nao              Sim   Excelente           8   
997        70-74  Branca      Nao              Sim   Muito boa           8   
998        70-74  Branca      Sim               No         Boa           6   
999        70-74   Preta      Sim               No   Excelente           7   

    Asma Doenca_renal Cancer_pele  
0    Sim          Nao         Sim  
1    Nao          Nao         Nao  
2    Sim          Nao         Nao  
3    Nao          Nao         Sim  
4    Nao          Nao         Nao  
..   ...          ...         ...  
995  Nao          Nao         Nao  
996  Nao          Nao         Nao  
997  Nao          Nao         Nao  
998  Sim          Nao         Nao  
999  Nao          Nao         Nao  

[1000 rows x 19 columns]

Informações Aninhadas:

In [87]:
dados_pacientes_2 = pd.read_json('/content/pacientes_2.json')

In [88]:
dados_pacientes_2

Pesquisa   Ano  \
0  Principais Indicadores de Doenca Cardiaca  2020   
1  Principais Indicadores de Doenca Cardiaca  2020   
2  Principais Indicadores de Doenca Cardiaca  2020   

                                           Pacientes  
0  {'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_bi...  
1  {'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_...  
2  {'ID': '03', 'Faixa_etaria': '65-69', 'Sexo_bi...

Para saber como está a estrutura do arquivo JSON:
[jsoncrack.com](https://jsoncrack.com/)

In [89]:
df_normalizado = pd.json_normalize(dados_pacientes_2['Pacientes'])

In [90]:
df_normalizado

ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0  01        55-59       Feminino  Branca  16.60     Sim            Nao   
1  02      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2  03        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]  
1   Muito boa           7                          [AVC]  
2   Muito boa           8               [diabetes, Asma]

Importante:

Na aula nós realizamos a normalização em um arquivo com o formato JSON. No entanto, a função json_normalize() aceita apenas um dicionário ou uma lista de dicionários. Por isso, no vídeo foi usada a estratégia de usar o código: pd.json_normalize(dados_pacientes_2['Pacientes']). Porém, se tentarmos usar parâmetros da função json_normalize em um arquivo JSON podem surgir erros. Para contornar isso, precisamos importar o módulo json e ler os arquivos conforme o código abaixo:

In [91]:
#Importando a biblioteca Pandas
import pandas as pd

#Importando o módulo JSON
import json

#Lendo o arquivo json usando o módulo Python JSON
with open('pacientes_2.json','r') as f:
    dados = json.loads(f.read())

#Normalizando os dados com os parâmetros record_path e meta
pd.json_normalize(dados, record_path='Pacientes', meta=['Pesquisa', 'Ano'])


ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0  01        55-59       Feminino  Branca  16.60     Sim            Nao   
1  02      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2  03        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  \
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]   
1   Muito boa           7                          [AVC]   
2   Muito boa           8               [diabetes, Asma]   

                                    Pesquisa   Ano  
0  Principais Indicadores de Doenca Cardiaca  2020  
1  Principais Indicadores de Doenca Cardiaca  2020  
2  Principais Indicadores de Doenca Cardiaca  2020

In [92]:
df_normalizado.to_json('historico_pacientes_normalizado.json')

In [93]:
pd.read_json('/content/historico_pacientes_normalizado.json')

ID Faixa_etaria Sexo_biologico    Raça    IMC Fumante Consumo_alcool  \
0   1        55-59       Feminino  Branca  16.60     Sim            Nao   
1   2      80 ou +       Feminino  Branca  20.34     Nao            Nao   
2   3        65-69      Masculino  Branca  26.58     Sim            Nao   

   Saude_fisica  Saude_mental Dificuldade_caminhar Atividade_fisica  \
0             3            30                  Nao              Sim   
1             0             0                  Nao              Sim   
2            20            30                  Nao              Sim   

  Saude_geral  Horas_sono                Problemas_saude  
0   Muito boa           5  [Diabetes, Asma, Cancer_pele]  
1   Muito boa           7                          [AVC]  
2   Muito boa           8               [diabetes, Asma]

# Arquivo HTML

In [96]:
dados_html = pd.read_html('/content/filmes.html')
dados_html

[                                                    0  \
 0                                                1998   
 1                                                1999   
 2                                                2000   
 3                                                2001   
 4                                                2002   
 5                                                2003   
 6                                                2004   
 7                                                2005   
 8                                                2005   
 9                                                2006   
 10                                               2006   
 11                                               2007   
 12                                               2008   
 13  .mw-parser-output .hlist dl,.mw-parser-output ...   
 
                                                     1  
 0                                          100 Movies  
 1            

In [97]:
type(dados_html)

list

In [98]:
len(dados_html)

2

In [99]:
top_filmes = dados_html[1]
top_filmes

Film  Release year              Director  \
0             Citizen Kane          1941          Orson Welles   
1               Casablanca          1942        Michael Curtiz   
2            The Godfather          1972  Francis Ford Coppola   
3       Gone with the Wind          1939        Victor Fleming   
4       Lawrence of Arabia          1962            David Lean   
..                     ...           ...                   ...   
118        Sophie's Choice          1982        Alan J. Pakula   
119  The Last Picture Show          1971     Peter Bogdanovich   
120     Do the Right Thing          1989             Spike Lee   
121           Blade Runner          1982          Ridley Scott   
122              Toy Story          1995         John Lasseter   

                              Production companies 1998 Rank 2007 Rank  
0                               RKO Radio Pictures         1         1  
1                            Warner Bros. Pictures         2         3  
2           Paramount Pictures, Alfran Productions         3         2  
3                  Selznick International Pictures         4         6  
4                                 Horizon Pictures         5         7  
..                                             ...       ...       ...  
118                              ITC Entertainment         -        91  
119                                BBS Productions         -        95  
120                  40 Acres and a Mule Filmworks         -        96  
121                The Ladd Company, Shaw Brothers         -        97  
122  Walt Disney Pictures, Pixar Animation Studios         -        99  

[123 rows x 6 columns]

In [100]:
top_filmes.to_html('top_filmes.html')

In [101]:
top_filmes.to_csv('top_filmes_1998.csv', index=False)

In [102]:
pd.read_csv('/content/top_filmes_1998.csv')

Film  Release year              Director  \
0             Citizen Kane          1941          Orson Welles   
1               Casablanca          1942        Michael Curtiz   
2            The Godfather          1972  Francis Ford Coppola   
3       Gone with the Wind          1939        Victor Fleming   
4       Lawrence of Arabia          1962            David Lean   
..                     ...           ...                   ...   
118        Sophie's Choice          1982        Alan J. Pakula   
119  The Last Picture Show          1971     Peter Bogdanovich   
120     Do the Right Thing          1989             Spike Lee   
121           Blade Runner          1982          Ridley Scott   
122              Toy Story          1995         John Lasseter   

                              Production companies 1998 Rank 2007 Rank  
0                               RKO Radio Pictures         1         1  
1                            Warner Bros. Pictures         2         3  
2           Paramount Pictures, Alfran Productions         3         2  
3                  Selznick International Pictures         4         6  
4                                 Horizon Pictures         5         7  
..                                             ...       ...       ...  
118                              ITC Entertainment         -        91  
119                                BBS Productions         -        95  
120                  40 Acres and a Mule Filmworks         -        96  
121                The Ladd Company, Shaw Brothers         -        97  
122  Walt Disney Pictures, Pixar Animation Studios         -        99  

[123 rows x 6 columns]

# Arquivo XML

In [106]:
dados_imdb = pd.read_xml('/content/imdb_top_1000.xml')
dados_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

In [107]:
dados_imdb.to_xml('filmes_imdb.xml')

# Arquivos SQL

In [108]:
import sqlalchemy

Na linha de baixo, escrevemos from sqlalchemy import. A primeira importação será create_engine, que serve para criar o motor, ou seja, a conexão com o banco de dados que o fará funcionar.

Na mesma linha, inserimos uma vírgula e a importação MetaData. Essa é uma classe que representa os meta dados do banco de dados, isso inclui informações sobre as tabelas, colunas e outros objetos.

Também importamos a classe Table que representa uma tabela em um banco de dados e é usada para manipular dados em uma tabela específica.

Por fim, importamos a função inspect, que permite inspecionar a estrutura do banco de dados.

In [109]:
from sqlalchemy import create_engine, MetaData, Table, inspect

Se a versão da SQLAlchemy for 2.0.16 ou uma versão mais atual, você deve atualizá-la para uma versão inferior a 2.0 com o seguinte código:

pip install --upgrade 'sqlalchemy<2.0'

In [110]:
sqlalchemy.__version__

'1.4.52'

In [111]:
engine = create_engine('sqlite:///:memory:')

Criamos o banco de dados. Para isso, criamos uma variável chamada engine. Dela, chamamos o create_engine(). Dentro das chaves abrimos aspas simples e escrevemos o banco de dados que será utilizado, 'sqlite:///:memory:'.

Nesse caso, usaremos o SQLite, um banco de dados que vem naturalmente instalado no Google Colab. Nesse trecho de código o memory indica que estamos usando um banco de dados local.

In [112]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'

In [113]:
dados = pd.read_csv(url)

In [114]:
dados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

Para colocá-las no nosso banco de dados utilizaremos a função dados.to_sql(), que deixará o dataframe no formato do banco. Dentro do parênteses, colocamos duas aspas simples e definimos o nome da tabela que será criada. Nesse caso será 'clientes'.

Na mesma linha inserimos uma vírgula e escrevemos a variável engine, que é o motor do banco. Por fim, escrevemos o parâmetro index=False.

In [115]:
dados.to_sql('clientes', engine, index=False)

438463

In [116]:
inspector = inspect(engine)

Criamos uma variável chamada inspector. Inserimos o símbolo de igual seguido da função inspect(). Dentro dela, vamos passar o engine e executar a célula.

Dessa forma, conseguimos verificar o que temos no banco de dados e inspecionar algumas informações.

Agora, podemos printar o nome das tabelas que temos dentro do banco de dados. Para fazer isso, escrveemos print(). Em seguida, passamos o inspector.get_table_names(), essa função devolve os nomes das tabelas que estão dentro do banco de dados.

In [117]:
print(inspector.get_table_names())

['clientes']


In [118]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda="Empregado"'

Quando trabalhamos com SQL utilizamos cláusulas, ou seja, palavras que possuem funções específicas para a consulta.

Lembrando que em SQL as cláusulas são escritas em caixa alta.

Sendo assim, após as aspas, escrevemos SELECT seguido de *. Esse asterisco indica que queremos selecionar todas as colunas da tabela.

Agora, precisamos especificar qual tabela é essa. Então, após * inserimos a cláusula FROM clientes.

Na mesma linha, escrevemos a cláusula WHERE, que filtra as informações, seguido do nome da coluna que queremos consultar Categoria_de_renda. Logo após escrevemos ="Empregado" e executamos.

**Estamos pedindo para selecionar todas as colunas da tabela clientes na qual a categoria de renda seja igual a "Empregado".**

Para ler uma consulta em SQL criaremos a variável empregados = pd.read_sql(). Dentro do parêntese, passamos a consulta e o motor do bando de dados, query, engine. Em seguida, a executamos.

In [119]:
empregados = pd.read_sql(query, engine)

In [120]:
empregados

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

Para salvá-la como uma nova tabela escrevemos empregados.to_sql(). Dentro do parêntese inserimos aspas simples e dentro dela escrevemos empregados. Adicionamos uma vírgula e passamos o parâmetro con=engine seguido de index=False e executamos.

In [121]:
empregados.to_sql('empregados',con=engine, index=False)

226059

Utilizamos o read_sql para lermos uma consulta, mas e se quisermos ler uma tabela inteira como a que acabamos de salvar?

Para isso, utilizamos a função pd.read_sql_table(). Dentro do parêntese inserimos aspas simples, seguido do nome da tabela que queremos executar 'empregados' e engine. Executamos em sequência.

**Lembre-se sempre dessa diferença, o read_sql permite ler uma consulta e o read_sql_table uma tabela completa**

In [122]:
pd.read_sql_table('empregados', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

Além disso, também podemos inserir outros parâmetros, como especificar quais colunas queremos que sejam lidas.

Para testarmos, copiamos a mesma linha de código que escrevemos anteriormente e colamos em uma nova linha.

Depois de engine, adicionamos o parâmetro colums=[ ]. Dentro de colchetes adicionamos aspas simples e dentro delas adicionamos as colunas que queremos visualizar, sendo: 'ID_cliente', 'Grau_escolaridade', 'Rendimento_anual'.

In [123]:
pd.read_sql_table('empregados', engine, columns=['ID_Cliente','Grau_escolaridade','Rendimento_anual'])

ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

In [124]:
query = 'SELECT * FROM clientes'

In [125]:
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

**Deletando item do banco de dados**

O cliente 5008808 está com o grau de escolaridade como Ensino médio. Porém, ele fez faculdade e deseja mudar para Ensino superior.

Para isso, em uma nova linha escrevemos a consulta query =''. Dentro das aspas usamos a clausula UPDATE seguido do nome da tabela clientes e a clausula SET.

Após, definimos qual coluna será alterada, então Grau_escolaridade. Inserimos o símbolo de igual, seguido da informação que queremos atualizar entre aspas duplas, nesse caso "Ensino superior".

Definimos onde isso será alterado WHERE ID_Cliente. Inserimos o símbolo de igual e o ID do cliente 5008808.

Agora, copiamos o mesmo código do contexto with que usamos anteriormente e colamos abaixo dessa nova consulta. Em seguida, executamos a célula. Dessa forma:

In [126]:
# Deletando itens do banco de dados
query = 'DELETE FROM clientes WHERE ID_Cliente="5008804"'
with engine.connect() as conn:
  conn.execute(query)

In [127]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52      Ensino médio       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

**Atualizando um banco de dados**

Suponhamos que a pessoa de ID 5008804 cancelou sua conta na instituição financeira. Isso significa que ela não faz mais parte do quadro de clientes.

Para tirá-la da tabela precisamos realizar uma consulta. Então, escrevemos query = ''. Dentro das aspas, inserimos a instrução DELETEseguido da cláusula FROM clientes. Agora, especificamos qual cliente será deletado, então, escrevemos WHERE seguido do nome da coluna ID_Cliente e o número do ID 5008804.

Apertamos "Enter" para a linha de baixo. Agora, fazemos um contexto with. Isso garante que a conexão com o banco de dados seja fechada corretamente após a execução da consulta. Depois, usamos o método engine.connect(), seguido de as conn.

Na linha de baixo, chamamos o conn.execute(query). Em seguida, executamos.

Com isso estamos usando um método chamado connect para estabelecer uma conexão com o banco de dados. Estamos pedindo para executar a query com o método execute que quando chamado, executa a instrução SQL diretamente no banco de dados, usando a conexão estabelecida.

In [128]:
# Atualizando itens do banco de dados
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente="5008808"'
with engine.connect() as conn:
  conn.execute(query)

In [129]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]